### ISSUE TITLE
Are there things I can strip out of the library to reduce memory usage?

### ISSUE THREAD

**Issue by richcj10** [arduino-libraries/ArduinoModbus#93]
Currently, this code takes up nearly 50 % of the Atmel 328p memory! and a lot of Dynamic memory. (over 50%)

I have removed TCP support since that was not needed and reduced frame size to help a bit. But is there another things I can strip to reduce size?

**Comment by per1234** [comment]
Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. Since this is neither, I'll close it. If anyone would like assistance with reducing the memory usage of the library, please post over on Arduino Forum:

https://forum.arduino.cc/
